name: landing test
favicon: null
layout_spectrum: 0.2353
typography_spectrum: 0.9495837190188468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf5f9'
    - '#000000'
    - '#00a1e5'
    - '#c62a00'
    - '#7b99a7'
  brandStrength: 0.6435575885698199
  lightness: 0.9395634653046727
  saturation: 0.7581579557154328
  rhythmicContrast: 0.9039057991467416
purpose: []
